### ISSUE TITLE
Give structure to code Base by making separate JS, CSS and HTML file

### ISSUE THREAD

**Issue by ayush-agarwal-190** [ayush-agarwal-190/hacktoberfest#11]

**Comment by ayush-agarwal-190** [comment]
> Assign it to me. I will:
> 
> * [ ]  rename hacktoberfest.html to index.html
> * [ ]  make a file named style.css in css folder
> * [ ]  make a file named index.js in js folder and will link it in index.html
> * [ ]  make a img folder
> 
> Anything else you ask for or any change you want? If everything is good please assign me to do this task.

Ok Go ahead with your task ,

**Comment by krishnabiradar3108** [comment]
can i work on this?

**Comment by RohanTheProgrammer** [comment]
Thank you bro. It was a nice experience working on this issue.😄

**Comment by ayush-agarwal-190** [comment]
> Thank you bro. It was a nice experience working on this issue.😄
> 
> Edit: Unfortunately your repo is shown as excluded on hacktoberfest website
Good Work,

**Comment by ayush-agarwal-190** [comment]
> Thank you bro. It was a nice experience working on this issue.😄
> 
> Edit: Unfortunately your repo is shown as excluded on hacktoberfest website

Rohan can you share me the link where it saying excluded,

**Comment by RohanTheProgrammer** [comment]
It is showing on [here](https://hacktoberfest.com/profile). You most probably will not be able to see it as it is showing on my profile. I am adding a screenshot of my profile page of hacktoberfest.com

![screenshot-hacktoberfest com-2022 10 01-00_48_44](https://user-images.githubusercontent.com/48507690/193341970-1f47e52e-ef60-4333-889c-6fa7f5902478.png)
